# Generated by Django 4.2.1 on 2023-06-21 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_order_name_order_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='name',
            new_name='all_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
    ]
