# Generated by Django 4.2.1 on 2023-07-25 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_purchasehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasehistory',
            name='all_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
