# Generated by Django 4.2.1 on 2023-07-03 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0006_product_date_release_alter_productimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_release',
            field=models.IntegerField(default=0),
        ),
    ]
