# Generated by Django 4.2.1 on 2023-07-10 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('storage', '0008_alter_rating_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourierOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('delivered', 'Delivered')], max_length=20)),
                ('products', models.ManyToManyField(to='storage.product')),
            ],
        ),
    ]
