# Generated by Django 4.2.1 on 2023-07-15 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff_status', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourierOrder',
        ),
    ]
