# Generated by Django 4.2.1 on 2023-06-11 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_productincart'),
    ]

    operations = [
        migrations.AddField(
            model_name='productincart',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
